abstract class ContactState {}
class InitialContactState extends ContactState{}
class TableContactState extends ContactState{}
class OpenDataContactState extends ContactState{}
class InsertDataContactState extends ContactState{}
class InsertSuccessDataContactState extends ContactState{}
class GetLoadingDataContactState extends ContactState{}
class ChangeBottomSheetContactState extends ContactState{}
class GetSuccessDataContactState extends ContactState{}
class ErrorGetDataContactState extends ContactState{}
class UpdateFavoriteDataContactState extends ContactState{}
class ErrorUpdateFavoriteDataContactState extends ContactState{}
class UpdateContactsDataContactState extends ContactState{}
class ChangeBottomNavigatorContactState extends ContactState{}
class AppDeleteContactState extends ContactState{}